---
- name: Install httpd
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
  - name: httpd
    yum:
      name: httpd
      state: present
  - name: service is started
    service:
      name: httpd
      state: started
  - name: openport 80 for httpd
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name: Restart firewall
    service:
      name: firewalld
      state: restarted
